"""fix: ajusta o id do order_items

Revision ID: 8635dab90a4c
Revises: 69238e07e58b
Create Date: 2026-09-11 08:05:15.791769

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8635dab90a4c"
down_revision: str | Sequence[str] | None = "69238e07e58b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("order_items") as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.Integer(),
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items",
        "id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
